//
// Created by Norlan on 1/9/2020.
//

#ifndef BASIC_00_EXAMPLE_NAVAJASUIZAGODCLASS_H
#define BASIC_00_EXAMPLE_NAVAJASUIZAGODCLASS_H


class NavajaSuizaGodClass {

};


#endif //BASIC_00_EXAMPLE_NAVAJASUIZAGODCLASS_H
